# ==================================================
# README 
# Install extention REST Client 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# ==================================================

###
GET http://localhost:5000/notes
Content-Type: application/json

@idNote=XsplWKhl
###
GET http://localhost:5000/notes/{{idNote}}
Content-Type: application/json

###
POST http://localhost:5000/notes 
Content-Type: application/json

{
  "title": "Vue JS",
  "tags": ["frontned", "css"],
  "body": "Best frontend engineer"
}

###
PUT http://localhost:5000/notes/{{idNote}} 
Content-Type: application/json

{
  "title": "React JS Updated",
  "tags": ["frontned", "css"],
  "body": "Best frontend engineer"
}

###
DELETE http://localhost:5000/notes/{{idNote}} 
Content-Type: application/json

# ==================================================
# LOCAL 
# ==================================================
###
GET http://localhost:5000/books
Content-Type: application/json


@id=dyBAtAUvI7FOPhzB
###
GET http://localhost:5000/books/{{id}}
Content-Type: application/json


###
POST http://localhost:5000/books 
Content-Type: application/json

{
  "name": "react Js",
  "year": 2010,
  "author": "John Doe",
  "summary": "Lorem ipsum dolor sit amet",
  "publisher": "Dicoding Indonesia",
  "pageCount": 100,
  "readPage": 100,
  "reading": true
}

###
PUT http://localhost:5000/books/{{id}} 
Content-Type: application/json

{ 
  "name": "Nuxt Js mastering",
  "year": 2010,
  "author": "John Doe",
  "summary": "Lorem ipsum dolor sit amet",
  "publisher": "Dicoding Indonesia",
  "pageCount": 100,
  "readPage": 10,
  "reading": false
}

###
DELETE http://localhost:5000/books/{{id}} 
Content-Type: application/json


# ==================================================
# PROD
# ==================================================

@url_server=http://52.77.218.216:5000
@book_id=e4CPO0BjJ6Ck22YY

###
POST {{url_server}}/books 
Content-Type: application/json

{
  "name": "react",
  "year": 2010,
  "author": "John Doe",
  "summary": "Lorem ipsum dolor sit amet",
  "publisher": "Dicoding Indonesia",
  "pageCount": 100,
  "readPage": 10,
  "reading": false
}


###
GET {{url_server}}/books
Content-Type: application/json

###
GET {{url_server}}/books/{{book_id}}
Content-Type: application/json

###
PUT {{url_server}}/books/{{book_id}} 
Content-Type: application/json

{ 
  "name": "Nuxt Js mastering",
  "year": 2010,
  "author": "John Doe",
  "summary": "Lorem ipsum dolor sit amet",
  "publisher": "Dicoding Indonesia",
  "pageCount": 100,
  "readPage": 10,
  "reading": false
}

###
DELETE {{url_server}}/books/{{book_id}} 
Content-Type: application/json